"""'init'

Revision ID: 13c614f69d01
Revises: cf2db4442876
Create Date: 2020-03-27 12:24:58.752153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13c614f69d01'
down_revision = 'cf2db4442876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_davidson_dataset_cluster_index', table_name='davidson_dataset_cluster')
    op.drop_table('davidson_dataset_cluster')
    op.drop_index('ix_founta_dataset_cluster_index', table_name='founta_dataset_cluster')
    op.drop_table('founta_dataset_cluster')
    op.drop_index('ix_gao_dataset_cluster_index', table_name='gao_dataset_cluster')
    op.drop_table('gao_dataset_cluster')
    op.drop_table('davidson_dataset_train')
    op.drop_table('davidson_dataset_test')
    op.drop_index('ix_waseem_dataset_cluster_index', table_name='waseem_dataset_cluster')
    op.drop_table('waseem_dataset_cluster')
    op.add_column('label', sa.Column('round', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_label_round'), 'label', ['round'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_round'), table_name='label')
    op.drop_column('label', 'round')
    op.create_table('waseem_dataset_cluster',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('cluster_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('centroid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('positive', mysql.TEXT(), nullable=True),
    sa.Column('negative', mysql.TEXT(), nullable=True),
    sa.Column('keywords', mysql.TEXT(), nullable=True),
    sa.CheckConstraint('(`centroid` in (0,1))', name='waseem_dataset_cluster_chk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_waseem_dataset_cluster_index', 'waseem_dataset_cluster', ['index'], unique=False)
    op.create_table('davidson_dataset_test',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('label', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('round', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('davidson_dataset_train',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('label', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('round', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('gao_dataset_cluster',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('cluster_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('centroid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('positive', mysql.TEXT(), nullable=True),
    sa.Column('negative', mysql.TEXT(), nullable=True),
    sa.Column('keywords', mysql.TEXT(), nullable=True),
    sa.CheckConstraint('(`centroid` in (0,1))', name='gao_dataset_cluster_chk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_gao_dataset_cluster_index', 'gao_dataset_cluster', ['index'], unique=False)
    op.create_table('founta_dataset_cluster',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('cluster_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('centroid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('positive', mysql.TEXT(), nullable=True),
    sa.Column('negative', mysql.TEXT(), nullable=True),
    sa.Column('keywords', mysql.TEXT(), nullable=True),
    sa.CheckConstraint('(`centroid` in (0,1))', name='founta_dataset_cluster_chk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_founta_dataset_cluster_index', 'founta_dataset_cluster', ['index'], unique=False)
    op.create_table('davidson_dataset_cluster',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('cluster_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('centroid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('positive', mysql.TEXT(), nullable=True),
    sa.Column('negative', mysql.TEXT(), nullable=True),
    sa.Column('keywords', mysql.TEXT(), nullable=True),
    sa.CheckConstraint('(`centroid` in (0,1))', name='davidson_dataset_cluster_chk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_davidson_dataset_cluster_index', 'davidson_dataset_cluster', ['index'], unique=False)
    # ### end Alembic commands ###
