"""init

Revision ID: cf2db4442876
Revises: 
Create Date: 2020-02-13 11:29:37.411744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2db4442876'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_batch'), 'label', ['batch'], unique=False)
    op.create_index(op.f('ix_label_dataset'), 'label', ['dataset'], unique=False)
    op.create_index(op.f('ix_label_row_id'), 'label', ['row_id'], unique=False)
    op.create_index(op.f('ix_label_user_id'), 'label', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_label_user_id'), table_name='label')
    op.drop_index(op.f('ix_label_row_id'), table_name='label')
    op.drop_index(op.f('ix_label_dataset'), table_name='label')
    op.drop_index(op.f('ix_label_batch'), table_name='label')
    op.drop_table('label')
    # ### end Alembic commands ###
